theme: jekyll-theme-architect
title: Computer Programming Blog
email: hmm8816@naver.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mirim6235
